drop table mes_flow;
drop table MES_FLOW_OPER;
drop table MES_LOC;
drop table MES_LOT;
drop table MES_LOT_COMP;
drop table MES_LOT_HIST;
drop table MES_MAT;
drop table MES_MAT_COMP;
drop table MES_OPER 
drop table MES_ORDER;
drop table MES_TEST_STATUS;
